<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_5strConcat" Id="{0acfa609-7eb4-476f-9646-e5afd72dd055}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_5strConcat : T_DEFAULT_STR		// Concatenates 4 strings
VAR_INPUT
	iStr1:		T_DEFAULT_STR;
	iStr2:		T_DEFAULT_STR;
	iStr3:		T_DEFAULT_STR;
	iStr4:		T_DEFAULT_STR;
	iStr5:		T_DEFAULT_STR;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_5strConcat := CONCAT(FC_4strConcat(iStr1, iStr2, iStr3, iStr4),iStr5);]]></ST>
    </Implementation>
    <LineIds Name="FC_5strConcat">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>