<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_6strConcat" Id="{96264cbe-6f80-4c4e-a33f-b91da96fab0f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_6strConcat : T_DEFAULT_STR		// Concatenates 4 strings
VAR_INPUT
	iStr1:		T_DEFAULT_STR;
	iStr2:		T_DEFAULT_STR;
	iStr3:		T_DEFAULT_STR;
	iStr4:		T_DEFAULT_STR;
	iStr5:		T_DEFAULT_STR;
	iStr6:		T_DEFAULT_STR;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_6strConcat := CONCAT(FC_5strConcat(iStr1, iStr2, iStr3, iStr4, iStr5), iStr6);]]></ST>
    </Implementation>
    <LineIds Name="FC_6strConcat">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>