<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_7strConcat" Id="{668dd080-d6a5-4846-98db-a2a3812bb3f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_7strConcat : T_DEFAULT_STR
VAR_INPUT
	iStr1:		T_DEFAULT_STR;
	iStr2:		T_DEFAULT_STR;
	iStr3:		T_DEFAULT_STR;
	iStr4:		T_DEFAULT_STR;
	iStr5:		T_DEFAULT_STR;
	iStr6:		T_DEFAULT_STR;
	iStr7:		T_DEFAULT_STR;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_7strConcat := CONCAT(FC_6strConcat(iStr1, iStr2, iStr3, iStr4, iStr5, iStr6), iStr7);
]]></ST>
    </Implementation>
    <LineIds Name="FC_7strConcat">
      <LineId Id="2" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>