<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_GetLocalTimeStringSecAccuracy" Id="{3e806724-c7ba-41aa-9bf2-9e94b3965a75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_GetLocalTimeStringSecAccuracy : T_SHORT_STR	// Returns the local time as short string, eg. '08:02:21 AM'.
													// Use E_REGIO_SELECTION at FB_CycleStart for a different format.
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_GetLocalTimeStringSecAccuracy := IING.localTimeSecAccuracy;]]></ST>
    </Implementation>
    <LineIds Name="FC_GetLocalTimeStringSecAccuracy">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>