<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_GetLocalTimeStringMinAccuracy" Id="{396b1c6b-b1f5-44d4-9835-57f39def515d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_GetLocalTimeStringMinAccuracy : T_SHORT_STR	// Returns the local time as short string, eg. '08:02 AM'.
													// Use E_REGIO_SELECTION at FB_CycleStart for a different format.
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_GetLocalTimeStringMinAccuracy := IING.localTimeMinAccuracy;]]></ST>
    </Implementation>
    <LineIds Name="FC_GetLocalTimeStringMinAccuracy">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>