<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_CycleEnd" Id="{fe038198-15a1-4868-a84a-413716c8e22c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CycleEnd		// Must always be the last call in PLC MAIN, does necessary things needed in every project
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="FB_CycleEnd">
      <LineId Id="2" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>