<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FC_GetMax3Lreals" Id="{fcd6ed51-5f93-4631-92d9-f2f794a5acfa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC_GetMax3Lreals : LREAL		// Returns the maximum of specified values
VAR_INPUT
	iLreal1:	LREAL;
	iLreal2:	LREAL;
	iLreal3:	LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FC_GetMax3Lreals := MAX(iLreal1, iLreal2);
FC_GetMax3Lreals := MAX(FC_GetMax3Lreals, iLreal3); 
]]></ST>
    </Implementation>
    <LineIds Name="FC_GetMax3Lreals">
      <LineId Id="2" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>