<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="IncINT" Id="{7b95fc8e-a3f0-4c3d-b28a-468cad96c581}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IncINT : INT				// Increments the given UINT value
VAR_IN_OUT
	ioNum:	INT;		// Value to increment
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IncINT := ioNum := ioNum + 1;
]]></ST>
    </Implementation>
    <LineIds Name="IncINT">
      <LineId Id="2" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>