<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="IncUDINT" Id="{d1295a8b-3754-4a8c-87df-265ebfe748cc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IncUDINT : UDINT		// Increments the given UINT value
VAR_IN_OUT
	ioNum:	UDINT;		// Value to increment
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IncUDINT := ioNum := ioNum + 1;
]]></ST>
    </Implementation>
    <LineIds Name="IncUDINT">
      <LineId Id="2" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>